FROM golang:latest

VOLUME /go/src/da-vinci

# In case you face TESSDATA_PREFIX error, you minght need to set env vars
# to specify the directory where "tessdata" is located.
ENV TESSDATA_PREFIX=/usr/share/tesseract-ocr

# Versions
# Leptonica 1.74.1
# Tesseract 3.04.01
RUN apt-get update -qq

# You need librariy files and headers of tesseract and leptonica.
# When you miss these or LD_LIBRARY_PATH is not set to them,
# you would face an error: "tesseract/baseapi.h: No such file or directory"
RUN apt-get install -y -qq libtesseract-dev libleptonica-dev

# Load languages.
# These {lang}.traineddata would b located under ${TESSDATA_PREFIX}/tessdata.
RUN apt-get install -y -qq tesseract-ocr-eng

WORKDIR /go/src/da-vinci


ENTRYPOINT ["tail", "-f", "/dev/null"]